name: admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.1
  firebase_database: ^10.3.5
  firebase_messaging: ^14.7.9
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.15.3
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  date_format: ^2.0.7

flutter_icons:
  image_path: "assets/images/admin.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.0
  firebase_auth: ^4.14.1
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
